//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA46Team07B_ESNET_Project_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Account
    {
        public string EmployeeID { get; set; }
        public string Password { get; set; }
    }
}
