//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA46Team07B_ESNET_Project_v2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class facilitybookingEntities : DbContext
    {
        public facilitybookingEntities()
            : base("name=facilitybookingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee_Account> Employee_Accounts { get; set; }
        public virtual DbSet<Employee_Detail> Employee_Details { get; set; }
        public virtual DbSet<Facility_Status> Facility_Status { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Transaction_Record> Transaction_Records { get; set; }
    }
}
