//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA46Team07B_ESNET_Project_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility_Status
    {
        public string Facility { get; set; }
        public string Slot_9_10am { get; set; }
        public string Slot_10_11am { get; set; }
        public string Slot_11_12pm { get; set; }
        public string Slot_12_1pm { get; set; }
        public string Slot_1_2pm { get; set; }
        public string Slot_2_3pm { get; set; }
        public string Slot_3_4pm { get; set; }
        public string Slot_4_5pm { get; set; }
        public string Slot_5_6pm { get; set; }
        public string Slot_6_7pm { get; set; }
        public string Slot_7_8pm { get; set; }
        public string Slot_8_9pm { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
