//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA46Team07B_ESNET_Project_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Record
    {
        public int TransactionID { get; set; }
        public int MemberID { get; set; }
        public string Facility { get; set; }
        public System.DateTime Date { get; set; }
        public string TimeSlot { get; set; }
        public string status { get; set; }
    }
}
